### ISSUE TITLE
Spacing fix

### ISSUE THREAD

**Issue by Muhammad-Tahir-S** [the-nth-ace/kolo-frontend#11]
<img width="597" alt="Screenshot 2022-11-13 at 16 13 28" src="https://user-images.githubusercontent.com/65069483/201529096-b2812964-cb74-4e35-ac0a-3ff6ea686d49.png">
<img width="750" alt="Screenshot 2022-11-13 at 16 14 31" src="https://user-images.githubusercontent.com/65069483/201529109-71f73410-ca57-49da-bda8-2afce600e1fc.png">

There is space between the right section and the header in the design, gotta aim for pixel perfection.

**Comment by the-nth-ace** [comment]
Fi
